{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "redis-pubsub-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-pubsub-exporter.labels" . | nindent 4 }}
    {{- with .Values.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: redis-pubsub
      rules:
        {{- toYaml .Values.prometheusRule.rules | nindent 8 }}
{{- end }}
